export const Component = {
  Application: Symbol.for('Application'),
  LoggerInterface: Symbol.for('LoggerInterface'),
  ConfigInterface: Symbol.for('ConfigInterface'),
  DatabaseInterface: Symbol.for('DatabaseInterface'),
  UserServiceInterface: Symbol.for('UserServiceInterface'),
  UserModel: Symbol.for('UserModel'),
  OfferServiceInterface: Symbol.for('OfferServiceInterface'),
  OfferModel: Symbol.for('OfferModel'),
  ReviewServiceInterface: Symbol.for('ReviewServiceInterface'),
  ReviewModel: Symbol.for('ReviewModel'),
  UserController: Symbol.for('UserController'),
  OfferController: Symbol.for('OfferController'),
  ReviewController: Symbol.for('ReviewController'),
  ExceptionFilterInterface: Symbol.for('ExceptionFilterInterface'),
} as const;
