# Тестовые данные
GET http://localhost:3123/api HTTP/1.1

###

# Пользователи
## Регистрация пользователя

POST http://localhost:4000/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "uljjj@mail.com",
  "avatarUrl": "torrance.png",
  "name": "Jack",
  "typeUser": "pro",
  "password": "shining"
}

###

## Получить список всех объявлений

GET http://localhost:4000/offers/ HTTP/1.1
Content-Type: application/json

###
## Получение детальной информации о предложении

GET http://localhost:4000/offers/63ef53518c347d2beade860e HTTP/1.1
Content-Type: application/json

###
## Создание объявления

POST http://localhost:4000/offers/ HTTP/1.1
Content-Type: application/json

{
  "title": "гостевой дом Дом3",
  "description": "Гостиница с видом на озеро",
  "date": "2022-12-31T15:20:28.610Z",
  "city": {
    "latitudeCity": 12,
    "longitudeCity": 12,
    "nameCity": "string"

  },
  "previewImage": "https://11.react.pages.academy/static/hotel/5.jpg",
  "images": [
    "https://11.react.pages.academy/static/hotel/9.jpg",
    "https://11.react.pages.academy/static/hotel/1.jpg"
  ],
  "isPremium": 999,
  "isFavorite": true,
  "rating": 4,
  "type": "hotel",
  "bedrooms": "0",
  "maxAdults": 9,
  "price": 111,
  "conveniences": [
    "Laptop friendly workspace",
    "Baby seat",
    "Washer",
    "Towels"
  ],
  "userId": "63ef3a35903666ed8acf792a",
  "location": {
    "latitude": 12,
    "longitude": 12
  }
}

###
## Редактирование объявления

PATCH http://localhost:4000/offers/63efa1758fa89d7c572e0f92 HTTP/1.1
Content-Type: application/json

{
  "title": "гостиница Портал Белуха"
}

###
## Удаление объявления

DELETE http://localhost:4000/offers/63ef6307fb90d353dda1f3e2 HTTP/1.1
Content-Type: application/json

###
## Создать комментарий
POST http://localhost:4000/reviews/ HTTP/1.1
Content-Type: application/json

{
  "comment": "Tекст",
  "offerId": "63efa1758fa89d7c572e0f92",
  "userId": "63ef3c33fd2ecf67ffe7990d",
  "rating": 2
}

###

## Список комментариев к объявлению
GET http://localhost:4000/offers/63efa1758fa89d7c572e0f92/comments HTTP/1.1

###

## Отправка аватарки пользователю

POST http://localhost:4000/users/63ef576c899585f505a2f98b/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="test.jpg"
Content-Type: image/png

< C:\Users\Николай\Desktop\test.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--


